In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
##sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'i am good girl',
    'i am good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am good girl',
 'i am good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## define the vocab size
voc_size=10000

In [5]:
##one hot reps
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5322, 5195, 58, 5227],
 [5322, 5195, 58, 278],
 [5322, 6915, 58, 6295],
 [3817, 8452, 3654, 1357],
 [3817, 8452, 3654, 8912],
 [9354, 5322, 449, 58, 5924],
 [1403, 202, 7176, 3654]]

In [6]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [9]:
#we make all the sentences of equal size
sent_length=8#max sent length
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)#pad seq basically jitte word kam rehte utte ya toh aage ya peeche 0 lga dete

In [10]:
embedded_docs

array([[   0,    0,    0,    0, 5322, 5195,   58, 5227],
       [   0,    0,    0,    0, 5322, 5195,   58,  278],
       [   0,    0,    0,    0, 5322, 6915,   58, 6295],
       [   0,    0,    0,    0, 3817, 8452, 3654, 1357],
       [   0,    0,    0,    0, 3817, 8452, 3654, 8912],
       [   0,    0,    0, 9354, 5322,  449,   58, 5924],
       [   0,    0,    0,    0, 1403,  202, 7176, 3654]])

In [11]:
#feature reps
dim=10#feature reps ki dimension


In [12]:
model=Sequential()
#model wrt embedding layer
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 163ms/step


array([[[-0.01837151,  0.02752269, -0.02448812, -0.01337351,
         -0.02294105,  0.03327734,  0.03245905,  0.03912491,
         -0.01850746, -0.01612917],
        [-0.01837151,  0.02752269, -0.02448812, -0.01337351,
         -0.02294105,  0.03327734,  0.03245905,  0.03912491,
         -0.01850746, -0.01612917],
        [-0.01837151,  0.02752269, -0.02448812, -0.01337351,
         -0.02294105,  0.03327734,  0.03245905,  0.03912491,
         -0.01850746, -0.01612917],
        [-0.01837151,  0.02752269, -0.02448812, -0.01337351,
         -0.02294105,  0.03327734,  0.03245905,  0.03912491,
         -0.01850746, -0.01612917],
        [-0.02914034, -0.01360825,  0.01859105, -0.02821577,
         -0.03560848, -0.03709449, -0.00556584, -0.00818541,
          0.01606114, -0.03742481],
        [ 0.02510866,  0.03867092,  0.04106661, -0.03192053,
          0.01937303,  0.01457789, -0.01789797, -0.00656706,
          0.0389829 ,  0.02152249],
        [-0.00151324, -0.04395474, -0.01458846, -0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 5322, 5195,   58, 5227])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 37ms/step


array([[-0.01837151,  0.02752269, -0.02448812, -0.01337351, -0.02294105,
         0.03327734,  0.03245905,  0.03912491, -0.01850746, -0.01612917],
       [-0.01837151,  0.02752269, -0.02448812, -0.01337351, -0.02294105,
         0.03327734,  0.03245905,  0.03912491, -0.01850746, -0.01612917],
       [-0.01837151,  0.02752269, -0.02448812, -0.01337351, -0.02294105,
         0.03327734,  0.03245905,  0.03912491, -0.01850746, -0.01612917],
       [-0.01837151,  0.02752269, -0.02448812, -0.01337351, -0.02294105,
         0.03327734,  0.03245905,  0.03912491, -0.01850746, -0.01612917],
       [-0.02914034, -0.01360825,  0.01859105, -0.02821577, -0.03560848,
        -0.03709449, -0.00556584, -0.00818541,  0.01606114, -0.03742481],
       [ 0.02510866,  0.03867092,  0.04106661, -0.03192053,  0.01937303,
         0.01457789, -0.01789797, -0.00656706,  0.0389829 ,  0.02152249],
       [-0.00151324, -0.04395474, -0.01458846, -0.04929599, -0.03988302,
        -0.00509576,  0.02498157, -0.01446911